# Generated by Django 4.2.11 on 2024-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="title",),
        migrations.AddField(
            model_name="note",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="note",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
