# Generated by Django 3.2 on 2024-04-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240407_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
