# Generated by Django 3.2 on 2024-04-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
